apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.24.0
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "0.5"      # Example CPU limit. Adjust as needed.
            memory: "256Mi" # Example memory limit. Adjust as needed.

        # Liveness 
        livenessProbe:
          httpGet:
            path: /  # Replace with your actual liveness check path
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        
        # Readiness
        readinessProbe:
          httpGet:
            path: /  # Replace with your actual readiness check path
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
